### PR TITLE
fix #1 add state to report

### LINKED ISSUE #1: Error report has no state
I noticed that `react-safe-render` exposes some parts of the component such as `displayName`, `props`, and the lifecycle method that threw the error. Is their a reason the `state` isn't exposed as well? Why not expose the component itself in the report?

An additional benefit other than your entire tree not getting locked up is that you can now reveal exactly which components in your app are failing and what state they were in when they failed. It would be useful to have as much information as possible. Thoughts?

### PR DESCRIPTION
**Pull request by vinnymac**

### CODE REVIEW

**Comment by skiano** [comment]
Is it possible for you to add a unit test in `__tests__/`? I probably wont get around to adding a test soon, and I think we shouldn't merge this without a test of the feature.

**Comment by vinnymac** [comment]
I plan on adding tests. I agree do not merge this yet. Figured I would just start this since it has been a month since any discussion has occurred. I happen to have the bandwidth to work on it.

**Comment by skiano** [comment]
terrific! thank you so much :)

**Comment by vinnymac** [comment]
I modified the existing ones you had where you were tweaking the props, but I also tweaked the state where possible and expect that change. Where it wasn't possible state can't be updated because of the failed render, so I refer to the initial state in those cases. If you'd like something changed or added let me know.

**Comment by skiano** [comment]
great!

**Comment by skiano** [comment]
I just released it as version 2.0.0 in NPM

**Pull request merged**
